[package]
name = "scrupper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["socks", "rustls-tls"] }
select = "0.5.0"
tokio = { version = "1", features = ["full"] }
